name: Build Flatpak

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: it.gnome.firme.yaml
          build-dir: flatpak-build

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: firme-flatpak
          path: flatpak-build/*.flatpak
